### ISSUE TITLE
跟进E站新版

### ISSUE THREAD

**Issue by OpportunityLiu** [OpportunityLiu/E-Viewer#105]
## 上游更新日志及讨论
https://forums.e-hentai.org/index.php?showtopic=225016
  
## todolist
- [x] 列表项解析 #102
- [x] 新标签历史页
- [x] “流行”页更新
- [x] “榜单”页更新
- [x] 用户主页更新
- [x] 跟进新的搜索选项，移除slave tag filter, 添加`页数过滤` 和`禁用标签过滤` 
- [x] 处理由于过滤器导致的页面合并和缺少结果
- [x] 跟进标签列表可访问情况
      https://forums.e-hentai.org/index.php?showtopic=225016&st=620&p=5382060&#entry5382060
- [x] 增加“关注”页（考虑设为首页或支持自定义首页并将此页设为默认） #92
- [x] 设置项更新 #104
- [ ] 添加 my tags 至应用设置 #92
- [ ] ...

**Comment by Sum59** [comment]
反馈一下新版本。。
问题：无法登陆，100%复现？
版本：系统1703，客户端2019.3.24
情况：卸载后重新安装，选择网页登陆后浏览器窗口不关闭，所以无法正常使用客户端。另一台电脑在没退出登陆下直接更新能正常使用。

**Comment by OpportunityLiu** [comment]
好像是有这个问题，不过貌似关了重开一下就好了？

**Comment by OpportunityLiu** [comment]
@Sum59 应该是网速太慢的原因

为了保证cookie和设置的完整性，登录以后需要访问表里站的设置页面、表站用户信息页、表站hathperks页，哪一个卡住就要用好久。
