### ISSUE TITLE
4.7.0 ARM版安装显示错误0x80073cf3

### ISSUE THREAD

**Issue by Moreki** [OpportunityLiu/E-Viewer#113]
dependency or conflict validation 
是否需要安装新的依赖环境？

**Comment by OpportunityLiu** [comment]
依赖更新过了，release note 提了

**Comment by Moreki** [comment]
额顺带一提，桌面版也不知道为什么登录后就没反应了
![image](https://user-images.githubusercontent.com/14026143/56112657-4cccdd80-5f8e-11e9-98a7-ea7255cecebc.png)

**Comment by Sum59** [comment]
> 额顺带一提，桌面版也不知道为什么登录后就没反应了
> ![图片](https://user-images.githubusercontent.com/14026143/56112657-4cccdd80-5f8e-11e9-98a7-ea7255cecebc.png)

https://github.com/OpportunityLiu/E-Viewer/issues/105#issuecomment-480723699
应该是网速问题吧。我登陆后挂了一会重开就好了。。
