### ISSUE TITLE
点击评论内特定链接会导致应用异常

### ISSUE THREAD

**Issue by TkzcM** [OpportunityLiu/E-Viewer#116]
点击评论内另一画廊某页的链接，跳转并返回后 评论、种子、图片 消失，有时会崩溃
改变窗口尺寸后恢复

![exbug](https://user-images.githubusercontent.com/45264418/56911286-2dca6180-6adf-11e9-90f5-aaa1891b4050.gif)

**Comment by OpportunityLiu** [comment]
好像并不能 100% 复现啊

m

**Comment by OpportunityLiu** [comment]
完全不知道发生了什么，不过还是改了改，你可以从appyevor装下最新的版本试试解决了没有

https://ci.appveyor.com/project/OpportunityLiu/exviewer/branch/dev

**Comment by TkzcM** [comment]
> 完全不知道发生了什么，不过还是改了改，你可以从appyevor装下最新的版本试试解决了没有
> 
> https://ci.appveyor.com/project/OpportunityLiu/exviewer/branch/dev

这个版本没问题了 : )
