### ISSUE TITLE
Exhentai关站了

### ISSUE THREAD

**Issue by zhihaofans** [OpportunityLiu/E-Viewer#122]
相关链接： https://forums.e-hentai.org/index.php?showtopic=229503

**Comment by OpportunityLiu** [comment]
🕯

**Comment by OpportunityLiu** [comment]
好像是要复活

**Comment by zhihaofans** [comment]
@OpportunityLiu  2020年关站信息被划掉了

**Comment by lukemin** [comment]
已经复活了！！
Site Retirement
A Message to the Community - E-Hentai Forums.png
For further official updates please check recent forum posts by Tenboro.
FAQ
Is the site shutting down?
This is no longer the case, at least for the foreseeable future.
Was anything deleted / lost?
No.
Can we upload / tag / comment on galleries?
Yes. All gallery activities are continuing as per usual.
Please do not intentionally mistag galleries, especially for tags involving controversial content. This will be met with a ban. If you are uncertain please post in the forums.
Should I send money?
Donations are appreciated but not necessary. This is not (and never was) a financial issue.
