### ISSUE TITLE
已经确定捐赠可以继续看到EX站的内容

### ISSUE THREAD

**Issue by sdshdv** [OpportunityLiu/E-Viewer#123]
![QQ图片20190730182448](https://user-images.githubusercontent.com/28926503/62122261-dadb9280-b2f7-11e9-88a2-d355de853b55.png)
打开 https://e-hentai.org/bitcoin.php 选择捐赠成为铜星，也就是最少20刀就能在E站看到Ex站的内容，可以在E站搜索到萝莉正太本。
对于有需要的人可以尝试,如果手头钱不多的可以选择暂时去哔咔或者N站

**Comment by OpportunityLiu** [comment]
问题是E站主站也要关吧。。
