### ISSUE TITLE
ExHentai not work without "igneous" cookie

### ISSUE THREAD

**Issue by mixa3607** [OpportunityLiu/E-Viewer#124]
If request not contain "igneous" cookie server return:
`<html><body style="background-color:white;text-align:center"><img src="https://exhentai.org/img/kokomade.jpg" /></body></html>`
When i add "igneous=<hex>" to request server return normal response.

Test with fiddler custom scripts:
`static function OnBeforeRequest(oSession: Session) {
		if (oSession.HostnameIs("exhentai.org")) {
			FiddlerObject.log("Add igneous cookie to exhentai.org");
			oSession.oRequest["Cookie"] = (oSession.oRequest["Cookie"] + ";igneous=<hex>");
		}}`

**Comment by OpportunityLiu** [comment]
![图片](https://user-images.githubusercontent.com/13471233/62470698-948da400-b7cd-11e9-9c37-12cbfb27230d.png)
Which url did you requested? It seems that cookie will be filled autometically as you send `ipb_member_id` and `ipb_pass_hash`.

Maybe it varys from accounts, e-hentai has many hidden rules for accounts with different register time, register IP, used IP, hath perks, donations, and so on.

**Comment by mixa3607** [comment]
I use ex with russia ip, no donations, no perks.
For example. In browser ex work with igneous, without i get https://exhentai.org/img/kokomade.jpg.
In ehviewer for android igneous cookie support implemented and all work.

**Comment by OpportunityLiu** [comment]
This should be fixed in the latstest release.
A new textbox for igneous cookie has beed added.

If you have more concerns, feel free to reopen or open new issues. :)

**Comment by mixa3607** [comment]
In latest release ex works! thanks.
