### ISSUE TITLE
Fix login for countries with blocked e-hentai

### ISSUE THREAD

**Issue by mixa3607** [OpportunityLiu/E-Viewer#125]
1) In russia e-hentai in self block (problems with law)
2) by default for russia IPs site show Cloudflare anti ddos page

For login, program get e-hentai.org/uconfig.php => get code 403 by cloudflare or "This content is not available in Russia.RU" by site => program notice  "status code not indicate success (403)"
If i enable proxy/vpn over other country, login return success code.
Easy solve: add "Force|NoCheck" checkbox in login window

**Comment by OpportunityLiu** [comment]
Check has been marked as optional on new commit.

Now logon can be done while e-hentai.org is blocked (forums.e-hentai.org accessible).
You can get new packege from CI.
https://ci.appveyor.com/project/OpportunityLiu/exviewer/branch/dev

**Comment by OpportunityLiu** [comment]
This should be fixed in latest release.
