### ISSUE TITLE
error and accessibility

### ISSUE THREAD

**Issue by jung679** [OpportunityLiu/E-Viewer#126]
I'm sorry because I'm Korean 
can not English

1.

Unable to reinstall after deleting program
(Perfectly Can not be deleted)

2.

In the program
no start favorites or Add setting

3.

add 
Desktop program shortcut

thank you

**Comment by OpportunityLiu** [comment]
1. Not my fault, maybe ask on Microsoft Community for support?
2. What's your meaning, the app has setting and favorites feature. What do you exactly want?
3. Just drag the app from start menu to desktop

**Comment by jung679** [comment]
Thank you for your reply

Favorites turn on at program startup → Provided by full search

I want to

**Comment by jung679** [comment]
Thank you for your reply

1.I want to know how to delete the program completely

2.Favorites turn on at program startup → Provided by full search   I want

**Comment by jung679** [comment]
Thank you for your reply

1.I want to know how to delete the program completely

2.Favorites turn on at program startup → Provided by full search   I want

**Comment by jung679** [comment]
> 1. 내 잘못이 아니라면 Microsoft 커뮤니티에 지원을 요청하십시오.
> 2. 당신의 의미는 무엇입니까, 응용 프로그램은 설정 및 즐겨 찾기 기능이 있습니다. 정확히 무엇을 원하십니까?
> 3. 시작 메뉴에서 데스크톱으로 앱을 드래그하기 만하면됩니다.

Thank you for your reply

1.I want to know how to delete the program completely

2.Favorites turn on at program startup → Provided by full search   I want

**Comment by jung679** [comment]
> 1. Not my fault, maybe ask on Microsoft Community for support?
> 2. What's your meaning, the app has setting and favorites feature. What do you exactly want?
> 3. Just drag the app from start menu to desktop

Thank you for your reply


1.I want to know how to delete the program completely (For reinstallation)

2.Favorites turn on at program startup → Provided by full search   (I want)

**Comment by jung679** [comment]
![스크린샷(123)](https://user-images.githubusercontent.com/20274593/62996516-f4f0a580-be9f-11e9-8424-c3a2ad710d7e.png)


No response

![스크린샷(124)](https://user-images.githubusercontent.com/20274593/62996501-e99d7a00-be9f-11e9-99d9-bf5ea0ff5f62.png)
![스크린샷(125)](https://user-images.githubusercontent.com/20274593/62996502-e99d7a00-be9f-11e9-85e8-13431812ba4f.png)
![스크린샷(126)](https://user-images.githubusercontent.com/20274593/62996503-ea361080-be9f-11e9-81b8-cfd415e6d36f.png)
![스크린샷(127)](https://user-images.githubusercontent.com/20274593/62996504-ea361080-be9f-11e9-9df6-40929c94bdd1.png)
![스크린샷(128)](https://user-images.githubusercontent.com/20274593/62996505-ea361080-be9f-11e9-911b-d664851b0202.png)

**Comment by OpportunityLiu** [comment]
right click - uninstall

**Comment by jung679** [comment]
> 오른쪽 클릭-제거
I removed appdata and program files. What should I do to solve this problem?


The program is not installed but it is installed. Also no response

**Comment by OpportunityLiu** [comment]
Ask here https://answers.microsoft.com/ko-kr/windows/forum, not me.

We can talk about the app, but I can't tell you everything about UWP.

**Comment by jung679** [comment]
> Ask here https://answers.microsoft.com/ko-kr/windows/forum, not me.
> 
> We can talk about the app, but I can't tell you everything about UWP.

thank you
