### ISSUE TITLE
8.8.0启动后闪退

### ISSUE THREAD

**Issue by Moreki** [OpportunityLiu/E-Viewer#127]
尝试过X86和X64，尝试过重置与完全删除后重新安装，更新依赖包，最终重启大法也没有用，皆启动就闪退。（主要也不知道闪退日志在哪里
系统版本：1903

**Comment by OpportunityLiu** [comment]
应用日志在 `~\AppData\Local\Packages\2289Opportunity.E-Viewer_x517s75edqf2e\LocalCache\AppLog.log`，但是闪退的话估计没有日志。

你可以看看事件查看器里有没有记录

**Comment by OpportunityLiu** [comment]
更新了一下依赖 https://raw.github.com/wiki/OpportunityLiu/E-Viewer/Dependencies/x64.zip 但是我觉得没啥卵用。

**Comment by Moreki** [comment]
![图片](https://user-images.githubusercontent.com/14026143/63836810-dcf34880-c9ac-11e9-8052-86cc5a930032.png)
出现啦！是死胡同！

**Comment by Moreki** [comment]
> 
> 
> 更新了一下依赖 https://raw.github.com/wiki/OpportunityLiu/E-Viewer/Dependencies/x64.zip 但是我觉得没啥卵用。

确实没有卵用hhhhh

**Comment by OpportunityLiu** [comment]
> 出现啦！是死胡同！

用powershell
```ps1
add-appxpackage ./*.appx
```

**Comment by OpportunityLiu** [comment]
试下CI上最新版本？
https://ci.appveyor.com/project/OpportunityLiu/exviewer/branch/dev/job/5scypdwn1oi1iuvd/artifacts

**Comment by OpportunityLiu** [comment]
感觉跟 app 无关，又是 win10 抽风了，UWP 就没正常过。

**Comment by Moreki** [comment]
👌 我试试 UWP饼很美好 现实很骨感

**Comment by Moreki** [comment]
![图片](https://user-images.githubusercontent.com/14026143/63838574-285b2600-c9b0-11e9-9f5b-7889a3dc4043.png)
装完那个依赖包之后，8.8.0还是闪退

测试版安装后同样闪退，可能是我电脑的问题？（其他UWP应用没有问题
我重置电脑之后再试吧。
