### ISSUE TITLE
方便同步一下代码吗？

### ISSUE THREAD

**Issue by TommyWOo82** [OpportunityLiu/E-Viewer#129]
朋友，我打算在你的UWP里做几个微调给自己用。克隆下来发现，里面少了几个文件。

ApplicationDataManager\Strings\strings.g.cs
ExClient\Strings\LocalizedStrings.g.cs
ExDawnOfDayTask\Strings\Strings.g.cs
ExViewer\Strings\Strings.g.cs

我试着看了好几个Branch和History，都没有这几个文件。能同步一下么？

**Comment by OpportunityLiu** [comment]
#42

**Comment by OpportunityLiu** [comment]
求你们先读一下readme
