### ISSUE TITLE
打开画廊时提示Format_BadDateTime

### ISSUE THREAD

**Issue by mushymuse** [OpportunityLiu/E-Viewer#131]
缩略图也无法加载。
只有部分画廊会出现这样的状况，还有一些是好的。
和表里站无关，表站画廊也会出现这个情况。
![2020-10-19 18-43-29](https://user-images.githubusercontent.com/41612504/96440980-526a4a00-123b-11eb-9fb3-8225fe62c00d.png)

**Comment by sam910037** [comment]
同樣問題

**Comment by Moreki** [comment]
同样问题，切换网络环境没有帮助。
![图片](https://user-images.githubusercontent.com/14026143/96953908-d61a8400-1524-11eb-8c12-c62905e02c75.png)
