### ISSUE TITLE
Win10m安装提示error:0x80073cfd 

### ISSUE THREAD

**Issue by Moreki** [OpportunityLiu/E-Viewer#135]
已经按提示安装了最新的依赖包。
![wp_ss_20201025_0001](https://user-images.githubusercontent.com/14026143/97098588-5d006580-16b9-11eb-8f6c-5f24122e3254.png)
![wp_ss_20201025_0002](https://user-images.githubusercontent.com/14026143/97098590-5f62bf80-16b9-11eb-8fc5-de7857eb454f.png)

话说是不是已经不再支持Win10m了呀。
；；

**Comment by OpportunityLiu** [comment]
现在编译出来连安装包扩展名都该msix了。。。那个appx只是我硬改扩展名传的一样的。。应该是没法支持win10m了。。

**Comment by OpportunityLiu** [comment]
就 RIP 吧。。

**Comment by Moreki** [comment]
Rip。。。上一个版本还是用的好好的😇

**Comment by OpportunityLiu** [comment]
用安卓吧，ehviewer也挺好用的 https://github.com/NekoInverter/EhViewer

**Comment by Moreki** [comment]
> 
> 
> 用安卓吧，ehviewer也挺好用的 https://github.com/NekoInverter/EhViewer
我的安卓手机在用，只是我安卓手机屏幕太小了（4.7寸），观感不如大屏好。
