### ISSUE TITLE
已处理证书链，但处理过程因根证书不受信任而终止(0x800B0109)

### ISSUE THREAD

**Issue by railannad** [OpportunityLiu/E-Viewer#136]
![image](https://user-images.githubusercontent.com/36919867/97108180-e38f6400-1706-11eb-8a31-1de82b7550a4.png)

已按照 #55 所描述卸载重装过证书,确保是储存在"受信任人"里
![image](https://user-images.githubusercontent.com/36919867/97108204-f86bf780-1706-11eb-8997-378b92f1d084.png)

四个依赖也全部安装完毕，只是安装Microsoft.VCLibs.x64.14.00.appx的时候提示我已经有了较新版本，请问第四个包是一定要用指定版本的吗?
![image](https://user-images.githubusercontent.com/36919867/97108220-0e79b800-1707-11eb-9199-a1dde0812011.png)
![image](https://user-images.githubusercontent.com/36919867/97108235-26513c00-1707-11eb-9feb-58f4b1d75eac.png)

**Comment by OpportunityLiu** [comment]
直接放受信任根证书试试吧。。我也不太清楚这个

**Comment by railannad** [comment]
> 直接放受信任根证书试试吧。。我也不太清楚这个

之前安装的是.msix，就出现上述报错。  今天无意间点到.appx,结果装好了，readme明明写的msix是安装包
也按照其他issue也设置好代理了,感谢大佬的软件，很好用。 这个issue就关了。

**Comment by OpportunityLiu** [comment]
可是这两是同一个文件啊，只改了个名字
