### ISSUE TITLE
新版本用了什麼新API要求系統版本在1903或以上

### ISSUE THREAD

**Issue by i9602097** [OpportunityLiu/E-Viewer#137]
<img width="489" alt="擷取" src="https://user-images.githubusercontent.com/18757629/97118907-c333c980-1747-11eb-88cd-c6015f109702.PNG">
早幾天用不了E-Viewer上來等bug修好<br/>
今天下了新版本安裝才發現系統要求提升到1903<br/>
這對有特殊理由要使用舊版Windows用戶不太友好吧！<br/>
如果無必要系統版本在1903以上希望能放寬限制到舊有系統要求

**Comment by OpportunityLiu** [comment]
说实话我也不记得了。。。这个项目已经转入维护很久了，这次动一下也只是改改bug。。。

如果你能帮忙看看的话我可以合并进来

**Comment by i9602097** [comment]
> 说实话我也不记得了。。。这个项目已经转入维护很久了，这次动一下也只是改改bug。。。
> 
> 如果你能帮忙看看的话我可以合并进来

呀！我只是用家沒有開發UWP應用的經驗
不過我在Microsoft網站上找到這應該只是項目中面向的內部版本問題
如果沒有用到新版本的特性
無必要把面向的內部版本調高
[选择 UWP 版本](https://docs.microsoft.com/zh-cn/windows/uwp/updates-and-versions/choose-a-uwp-version)

**Comment by Moreki** [comment]
> 
> 
> > 说实话我也不记得了。。。这个项目已经转入维护很久了，这次动一下也只是改改bug。。。
> > 如果你能帮忙看看的话我可以合并进来
> 
> 呀！我只是用家沒有開發UWP應用的經驗
> 不過我在Microsoft網站上找到這應該只是項目中面向的內部版本問題
> 如果沒有用到新版本的特性
> 無必要把面向的內部版本調高
> [选择 UWP 版本](https://docs.microsoft.com/zh-cn/windows/uwp/updates-and-versions/choose-a-uwp-version)

看了下你附上的链接，17134和16299都可以欸，8.8版本在1709上都可以使用和稳定运行。

**Comment by OpportunityLiu** [comment]
https://docs.microsoft.com/en-us/dotnet/standard/net-standard
 
最低应该只能到 16299 了，WM应该没办法了，我降级看看有没有啥问题吧

**Comment by OpportunityLiu** [comment]
试一下最新版本吧

**Comment by OpportunityLiu** [comment]
有什么问题可以再开
