### ISSUE TITLE
請問有辦法看日期被畫線的本子嗎？

### ISSUE THREAD

**Issue by orocannoneer** [OpportunityLiu/E-Viewer#139]
我已經存到favorite了，程式還是讀不到...希望加入直接導入網址的功能 #

**Comment by OpportunityLiu** [comment]
![图片](https://user-images.githubusercontent.com/13471233/101655408-8c5a0e80-3a7c-11eb-8481-7d9b50309e3b.png)

没问题啊

**Comment by OpportunityLiu** [comment]
导入网址也可以啊，你按<kbd>win</kbd>+<kbd>R</kbd>把URL粘进去选用e-viewer打开就行
