### ISSUE TITLE
E-hentai tag系统更新导致app无法正确解析。

### ISSUE THREAD

**Issue by jszhtian** [OpportunityLiu/E-Viewer#146]
原因：https://github.com/EhTagTranslation/Database/issues/98
位置：https://github.com/OpportunityLiu/E-Viewer/blob/ba79bebdc203673d86e50294f682766acbb35c40/ExClient/Tagging/Namespace.cs#L99
看上去应该要新增分类。等e-hentai tag彻底改好之后再处理。或者把不在匹配列表里的tag/group直接输出原始字符串。

**Comment by OpportunityLiu** [comment]
应该是没啥问题了
