### ISSUE TITLE
无法打开上传者为disowned的画廊

### ISSUE THREAD

**Issue by xiangluoming** [OpportunityLiu/E-Viewer#149]
打开上传者为(Disowned)的画廊的时候，显示“Value cannot be null"，但是其实在网页上这些画廊是可以查看的。

**Comment by OpportunityLiu** [comment]
没啥问题啊，能给个链接吗？

**Comment by xiangluoming** [comment]
https://e-hentai.org/g/1127839/06928fb7d9/ 比如这个。
打开来是这样的
![image](https://user-images.githubusercontent.com/18420821/147872480-c70158f2-6730-4443-8ebd-0bed5ea57133.png)
