### ISSUE TITLE
Multiple feature requests

### ISSUE THREAD

**Issue by HIRO0132** [OpportunityLiu/E-Viewer#150]
Features that I found useful

1, Automatically sort downloaded gallery into subfolders by gallery name

2, The scroll position and page of the search result in the search tab are cached even if it is switched to another tab.（If you search by some word or tag and switch tabs, it will change to the same scroll position as if you did not search.）

I hope this app will be even easier to use. Thanks

**Comment by OpportunityLiu** [comment]
1. This app is currently use image hash as file name to reduce download & storage when gallery revision updates.
2. The scroll position is memorized for each seacrh.
