### ISSUE TITLE
不挂t子用不了啊

### ISSUE THREAD

**Issue by tjddbc** [OpportunityLiu/E-Viewer#155]

**Comment by tjddbc** [comment]
老哥不是说里站不是能免t子的吗，我登录过了

**Comment by OpportunityLiu** [comment]
#143

**Comment by Onesade** [comment]
能用 大陆可以裸连的，你是加载不出来还是进不去？

**Comment by tjddbc** [comment]
uwp是正在加载更多画廊...网页是e-hentai.org&nbsp;的响应时间过长。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月6日(星期三) 下午3:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [OpportunityLiu/E-Viewer] 不挂t子用不了啊 (Issue #155)





 
能用 大陆可以裸连的，你是加载不出来还是进不去？
 
&mdash;

**Comment by tjddbc** [comment]
uwp是正在加载更多画廊...
网页是e-hentai.org 的响应时间过长。

**Comment by Onesade** [comment]
你先试试挂上梯子能不能进入里站，或者不挂梯子能不能进入外站

**Comment by Onesade** [comment]
实在不行用子系统装e-viewer for Android

**Comment by tjddbc** [comment]
不用我是win10，手机有app



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月6日(星期三) 下午4:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [OpportunityLiu/E-Viewer] 不挂t子用不了啊 (Issue #155)





 
实在不行用子系统装e-viewer for Android
 
&mdash;

**Comment by tjddbc** [comment]
挂了都行，不挂都不行，电信的宽带




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月6日(星期三) 下午4:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [OpportunityLiu/E-Viewer] 不挂t子用不了啊 (Issue #155)





 
你先试试挂上梯子能不能进入里站，或者不挂梯子能不能进入外站
 
&mdash;

**Comment by OpportunityLiu** [comment]
并没有直连功能，没说过，FAQ还教怎么用代理呢
