### ISSUE TITLE
ARM64版本

### ISSUE THREAD

**Issue by hathlife** [OpportunityLiu/E-Viewer#161]
现在ARM64的Windows平板越来越多，以后ms也会移除windows on arm的arm32支持，何时会在ci添加输出ARM64版本的工作流吗？
![image](https://user-images.githubusercontent.com/19867269/197339739-ec0a7df3-e09c-4a4e-a700-527efce504ae.png)

**Comment by OpportunityLiu** [comment]
发布了 ARM64 版本，我这里没有可以测试的设备，有问题新开issue讨论
