### ISSUE TITLE
E-Hentai网页升级后app报错

### ISSUE THREAD

**Issue by jszhtian** [OpportunityLiu/E-Viewer#162]
Ehentai更新后，App报告与服务器连接已重置。
Android的客户端也存在问题，只能打开第一页，推测由于网页改版导致问题。

**Comment by hathlife** [comment]
https://github.com/Ehviewer-Overhauled/Ehviewer/commit/02bd5badb9ab63a42a295298004e5a5bfb8b55bd

**Comment by OpportunityLiu** [comment]
所以e站啥时候更新啊，为啥只有ex更新。。
我可不想维护两个版本

**Comment by LzNOHentai** [comment]
> 所以e站啥时候更新啊，为啥只有ex更新。。 我可不想维护两个版本

表站已更新

**Comment by OpportunityLiu** [comment]
已经更新，还没有移除无效的搜索选项
