### ISSUE TITLE
评论区的链接无法跳转

### ISSUE THREAD

**Issue by xiangluoming** [OpportunityLiu/E-Viewer#165]
评论区的触感很奇怪，（触屏时）点一下弹一下，然后里面的链接也没法跳转过去，而是选中部分链接文本，是不是什么ui组件没弄好？

**Comment by OpportunityLiu** [comment]
反正之前是没有的，现在我手头已经没有相应的设备可以调试了，微软还把模拟器给砍了

**Comment by OpportunityLiu** [comment]
新版本应该修复了，如果还有问题，再新开issue
