### ISSUE TITLE
Unable to view galleries with error message: Value cannot be null.

### ISSUE THREAD

**Issue by hitosen** [OpportunityLiu/E-Viewer#171]
![Error Screenshot](https://github.com/OpportunityLiu/E-Viewer/assets/149200405/07e39d6f-1dd3-428c-8cf5-378722f71306)

Error screenshot attached.

It happens with all galleries, regardless of lanaguage.

**Comment by hitosen** [comment]
Through web, all galleries are accessable normally.

**Comment by OpportunityLiu** [comment]
Will be fixed in latest release
