### ISSUE TITLE
Error due to backend and DOM changes

### ISSUE THREAD

**Issue by asp1947** [OpportunityLiu/E-Viewer#177]
As of 2024-10-25, when accessing all galleries immediately after the changes are applied,
'attempted to divide by zero' error occurs.

**Comment by asp1947** [comment]
2024-10-25

- The previously announced backend and DOM changes are now live for a section of the site, let me know if you encounter any issues with this NOT related to outdated scripts.

https://forums.e-hentai.org/index.php?showtopic=244935

**Comment by OpportunityLiu** [comment]
I'll update the app after the changes go to stable.

**Comment by Liaozhaohe** [comment]
I wonder if there exists any temporary solution for fixing this issue before the app is updated
