### ISSUE TITLE
可以考虑添加幻灯片放映吗？

### ISSUE THREAD

**Issue by Moreki** [OpportunityLiu/E-Viewer#81]
如题，解放双手🙈🤣🤣

**Comment by OpportunityLiu** [comment]
认真的吗。。。

**Comment by Mapaler** [comment]
我觉得有必要，特别是游戏CG几百上千张的时候。手按累死。

**Comment by OpportunityLiu** [comment]
![default](https://user-images.githubusercontent.com/13471233/52536337-1c9d6e80-2d94-11e9-8399-cfa21dacaa49.png)
![default](https://user-images.githubusercontent.com/13471233/52536345-24f5a980-2d94-11e9-8c4f-52c7cc75b198.png)

**Comment by OpportunityLiu** [comment]
过两天发新版本

**Comment by Moreki** [comment]
:grinning:
