### ISSUE TITLE
修改翻页逻辑

### ISSUE THREAD

**Issue by OpportunityLiu** [OpportunityLiu/E-Viewer#96]
- [ ] 取消双击放大功能
- [ ] 单击两侧翻页，中间放大
   - [ ] 更多？
   - [ ] 自定义配置？

#85

**Comment by Mapaler** [comment]
放大缩小各是一个按键才对![](https://i.imgur.com/leYFpZv.png)

**Comment by OpportunityLiu** [comment]
想了想双击放大还是有用的
