### ISSUE TITLE
 阅读的时候能不能隐藏设置栏？

### ISSUE THREAD

**Issue by lukemin** [OpportunityLiu/E-Viewer#99]
如题

**Comment by OpportunityLiu** [comment]
点一下任意位置就隐藏了啊

**Comment by lukemin** [comment]
<img width="655" alt="default" src="https://user-images.githubusercontent.com/12003375/52793271-51693880-30a8-11e9-88d4-5c70c8b830fa.PNG">
没有隐藏啊

**Comment by OpportunityLiu** [comment]
要隐藏汉堡菜单请全屏
